### ISSUE TITLE
Recommended RAM for Db creation

### ISSUE THREAD

**Issue by blaize1st** [ToniWestbrook/paladin#31]
Hi,
It seems that Paladin requires huge amount of RAM for database generation (>256Gb), so what is recommended quantity of RAM using full Uniprot90 sequences?

Thank you: Blaize

**Comment by gundizalv** [comment]
I have the same problem. Whats the recommended quantity of RAM?

**Comment by gundizalv** [comment]
For an Uniref50.fasta file of 14 Gb. require a minimal of 180Gb of RAM. Took me 22105 seconds in a Intel Xeon with 8 cores and 220 Gb RAM
