### ISSUE TITLE
Piping fastq results in "-.pro"

### ISSUE THREAD

**Issue by mw55309** [ToniWestbrook/paladin#33]
Hi

I would like to cat my fastq directly in to paladin align and this seems to work ok, however, what that means is we end up with a file called "-.pro" in the current working directory

That in itself is not a problem, unless I want to run 50 samples in the same directory, in which case I assume the "-.pro" files will clash.

Is there a way to provide a prefix for this file in such instances?

Cheers
Mick

**Comment by twestbrookunh** [comment]
Hi Mick -

Apologies, I missed this ticket until now. Is this still something you wish to do?  If so, will you be running the PALADIN jobs in serial or parallel?  If in serial, you should be okay - that PRO file generated for the reads is just temporary, it will be overwritten next time PALADIN runs.  Let me know if you're looking to do the jobs in parallel though. Thanks
